### ISSUE TITLE
Blacklisted Weapons Config

### ISSUE THREAD

**Issue by PaulyJ1** [JaredScar/Badger-Anticheat#14]
So, I'm not sure where to start with PRs, but wanted to highlight something I've noticed. Which is why I'm putting an issue in instead.

In [client.lua#L174](https://github.com/JaredScar/Badger-Anticheat/blob/master/client.lua#L174) it mentions "Config.Components.BlacklistedWeapons".

However, looking at [config.lua#L4-L17](url) there is no component config for BlacklistedWeapons.

Probably an easy fix, but not something I can fix myself for a PR.

**Comment by PaulyJ1** [comment]
To add, I managed to get this - 
![20201220150557_1](https://user-images.githubusercontent.com/12805807/102716701-70a10480-42d5-11eb-85f3-141a3b2dabd9.jpg)

**Comment by JaredScar** [comment]
This should be fixed now. Thank you.
