### ISSUE TITLE
Latest couple of versions seem to cause crashing

### ISSUE THREAD

**Issue by PaulyJ1** [JaredScar/Badger-Anticheat#17]
Hey, Badger!

I have been using this script for quite a while now. My most current version is the one where you removed anti-keys.

I've been wanting to update to your most recent version to take advantage of the anti-weapons, etc. However, whilst trying to use it on my test server, the server crashes before fully loading in. (ie. I crash on "the bridge").

### Bit of insight into my Server.
**Framework:** ESX 1.2 aka ESX 1-final
**Screenshot Basic:** Yes
**Discord Screenshot:** Yes
**Ace Perms:** Yes

**Comment by JaredScar** [comment]
You'll have to mess around with settings. Certain settings will interfere with other scripts and cause crashes. I can't do that for you and won't.
