### ISSUE TITLE
FiveM crashing

### ISSUE THREAD

**Issue by yoshi-stunts** [JaredScar/Badger-Anticheat#19]
Hey, so I installed the Anticheat, I tested No-clipping and spectating without setting up ace perms and got banned for both, which is a good thing, means it's working as intended.   However, when I did set up ace perms, my FiveM crashes within 5 seconds of loading in.  If I take away admin perms from myself, I have no issues (aside from the anticheat doing its job when I no-clip or spectate)  or if I remove the ace perm for the anticheat, I also then have no issues.   
![fivem not responding](https://user-images.githubusercontent.com/79552583/108948617-d04ac180-7630-11eb-8d6a-b31318ffe766.PNG)
![ace perm in server cfg](https://user-images.githubusercontent.com/79552583/108948643-da6cc000-7630-11eb-8bf1-80fd4ea2a0e7.png)

**Comment by LukeM03** [comment]
same issue

**Comment by JaredScar** [comment]
So if you don't have the bypass permission, you don't crash?

**Comment by justmaiklas** [comment]
Created pull request

**Comment by yoshi-stunts** [comment]
> So if you don't have the bypass permission, you don't crash?

Correct, if I don't give myself the bypass permission, I don't crash... but obviously can't spectate or no clip without getting banned.  But changing the client.lua to what @justmaiklas said fixed it.

**Comment by JaredScar** [comment]
This was fixed with latest pull request. Thanks @justmaiklas

**Comment by yoshi-stunts** [comment]
How would one take away the server side chat message whenever someone is banned or unbanned?  Don't really want that to show up in chat for everyone especially when people are streaming.

**Comment by justmaiklas** [comment]
> How would one take away the server side chat message whenever someone is banned or unbanned? Don't really want that to show up in chat for everyone especially when people are streaming.


Comment out this line:
` TriggerClientEvent('chatMessage', -1, '^3[^6Badger-Anticheat^3] ^0Player ^1' .. playerName .. ' ^0has been unbanned from the server by ^2CONSOLE'); `
And change where command is not exucuted by console: "-1" to source
Example:
From:
`TriggerClientEvent('chatMessage', -1......`
To:
`TriggerClientEvent('chatMessage', src......`

**Comment by yoshi-stunts** [comment]
@justmaiklas THANK YOU!!

**Comment by justmaiklas** [comment]
Do the same for ban command
