### ISSUE TITLE
Players being banned for using vMenu teleport

### ISSUE THREAD

**Issue by yoshi-stunts** [JaredScar/Badger-Anticheat#21]
So, as the title states I've had multiple players in my server get banned when they teleport through vMenu.   It's random however, when testing this script I TPed numerous times through vMenu and never had this issue as well as multiple players on my server teleporting with no issue.  But every so often someone does get banned from it which creates an issue.

**Comment by JaredScar** [comment]
Did not follow instructions. There is a reason why this happens. Give your staff the bypass permission...
