### ISSUE TITLE
SCRIPT ERROR: @Badger-Anticheat/server.lua:187: attempt to call a nil value (global 'ExtractIdentifiers')

### ISSUE THREAD

**Issue by Musiker15** [JaredScar/Badger-Anticheat#22]
Hey my console says:
SCRIPT ERROR: @Badger-Anticheat/server.lua:187: attempt to call a nil value (global 'ExtractIdentifiers')

It is impossible to join the server.
https://prnt.sc/12bti8l

I installed the newest Version of Badger-Anticheat. Please help me fix that.

**Comment by JaredScar** [comment]
Issue on your end. Notice how no one else has reported this

**Comment by PoddaMV** [comment]
Hi I download and run the script first time when I login it work then I got the same error  what Musiker having
